print("Sontu Alexandra")
print("11.01.2005")
print("eleva in clasa a 10''D'')
print("Republica Moldova,municipiul Balti")
print("alexandrasontu@gmail.com")
print("078937110")
print("limba romana,limba germana,limba rusa,limba engleza")
print("strada Bulgara 72\2")
